#!/bin/bash
export PATH="$PWD/.gobincache:$PATH"
set -x -e -o pipefail
go generate

hadolint Dockerfile
hadolint Dockerfile.chainguard

shellcheck scripts/*

golangci-lint --version
golangci-lint run --verbose --out-format=github-actions

gotestsum -- -race -timeout=60s "$@" ./...
