#!/bin/bash
export PATH="$PWD/.gobincache:$PATH"
set -x -e -o pipefail
go generate

hadolint Dockerfile

shellcheck scripts/*

go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.47.3
golangci-lint run --version --verbose --out-format=github-actions

gotestsum -- -race -timeout=60s "$@" ./...
